spring:
  datasourse:
    username: database
    password: akbala
    url: jdbc:mysql://localhost:8889/javaProject
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect